### PR TITLE
Correct Take all town Snapshot

### PR DESCRIPTION
**Pull request by D1n0Bot**
Change
If $TakeSS = true to 1

### CODE REVIEW

**Comment by ahmadsafar** [comment]
Dont make a Pull request. you are contribute to this repo, so all your changes sync in here

**Comment by DkEd** [comment]
Ok, I'm sorry. I'm new to github

Kind regards,

Jason.

**Comment by ahmadsafar** [comment]
not you, sorry

**Comment by ahmadsafar** [comment]
@D1n0Bot Dont make a Pull request. you are contribute to this repo, so all your changes sync in here

**Comment by ahmadsafar** [comment]
@DkEd wrong to comment here, ok no prob

**Pull request merged**
